### ISSUE TITLE
Ecto compiles on Elixir 1.0.0-rc1 but not on 1.0.0

### ISSUE THREAD

**Issue by ghost** [elixir-ecto/ecto#274]
Hi folks,

I have one project that is compiling fine under Elixir 1.0.0-rc1 but fails when using Elixir master branch that is actually versioned with '1.0.0'.

```
==> ecto
warning: the dependency ecto requires Elixir "~> 0.15.0" but you are running on v1.0.0
Compiled lib/ecto/adapter/migrations.ex
Compiled lib/ecto/adapter/test_transactions.ex
Compiled lib/ecto/adapter/storage.ex
Compiled lib/ecto/adapter.ex
Compiled lib/ecto/adapter/transactions.ex
Compiled lib/ecto/adapters/postgres/worker.ex
Compiled lib/ecto/associations.ex
Compiled lib/ecto/migration.ex
Compiled lib/ecto/associations/belongs_to.ex
Compiled lib/ecto/migrator.ex
Compiled lib/ecto/model.ex
Compiled lib/ecto/associations/has_one.ex
Compiled lib/ecto/model/validations.ex
Compiled lib/ecto/query/distinct_builder.ex
Compiled lib/ecto/query/from_builder.ex
Compiled lib/ecto/query/builder_util.ex
Compiled lib/ecto/query.ex
Compiled lib/ecto/exceptions.ex
Compiled lib/ecto/associations/assoc.ex
Compiled lib/ecto/query/group_by_builder.ex
Compiled lib/ecto/query/having_builder.ex
Compiled lib/ecto/query/limit_offset_builder.ex
Compiled lib/ecto/query/lock_builder.ex

== Compilation error on file lib/ecto/query/join_builder.ex ==
** (CompileError) lib/ecto/query/join_builder.ex:70: function 'nil?'/1 undefined
    (stdlib) lists.erl:1336: :lists.foreach/2
    (stdlib) erl_eval.erl:657: :erl_eval.do_apply/6
    (elixir) src/elixir.erl:175: :elixir.erl_eval/3
    (elixir) src/elixir.erl:163: :elixir.eval_forms/4
    (elixir) src/elixir_lexical.erl:17: :elixir_lexical.run/3
    (elixir) src/elixir.erl:175: :elixir.erl_eval/3

could not compile dependency ecto, mix compile failed. You can recompile this dependency with `mix  deps.compile ecto` or update it with `mix deps.update ecto`
```

I would very much appreciate any help or guidance :)
