### ISSUE TITLE
Ecto should warn or throw a runtime error if an inferred field doesn't exist on a schema

### ISSUE THREAD

**Issue by hanrelan** [elixir-ecto/ecto#1948]
Right now, if Ecto infers for example a foreign key  based on the referenced module name and that foreign key does not exist on the schema, Ecto will silently allow it.
It would help if Ecto emitted a warning or threw a runtime error in this situation.

One example is the following schema:
```
In NoteModel:
  schema "notes" do
    has_one :snapshot, SnapshotModel
  end

In SnapshotModel:
  schema "snapshots" do
    belongs_to :note, NoteModel
  end
```
In this case, the "notes" schema infers a `note_model_id` on "snapshots", where no such field exists, but Ecto doesn't warn or throw an error

**Comment by josevalim** [comment]
We cannot do that at compilation time because it can generate cyclic dependencies. I believe an error would show up though when building queries.

**Comment by michalmuskala** [comment]
@josevalim It's not about building queries. The issue arose with `put_assoc` not setting correct foreign key. There was no error or anything - just silent failure.

I'm aware a compile-time warning is impossible, but a runtime one should be possible.

**Comment by josevalim** [comment]
@michalmuskala can you please complement with more information though? I am still unsure of what needs to be fixed or how to reproduce the issue mentioned here.

Feel free to reopen btw.

**Comment by michalmuskala** [comment]
@josevalim added a failing test in https://github.com/elixir-ecto/ecto/commit/ea9fb8e2efeabb36fd5c29d2646f91b048d1fd21

The issue is we set the `permalinked_comment.permalink_id` field as inferred, even though the struct has no such field (!) - breaking the struct itself.

**Comment by michalmuskala** [comment]
We should checks this additionally for `build_assoc`. So overall the change should affect:
* `build_assoc`
* `put_assoc`
* `cast_assoc`
* potentially when setting the association directly in the parent schema and passing everything directly to `Repo.insert!`
