### ISSUE TITLE
using `type/2` with `coalesce/2` is not a valid query expression

### ISSUE THREAD

**Issue by zachdaniel** [elixir-ecto/ecto#2500]
### Environment

* Elixir version (elixir -v): 1.6.3
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): PostgreSQL 9.6
* Ecto version (mix deps): 
* Database adapter and version (mix deps): master
* Operating system: MacOS

### Current behavior

```elixir
from row in "posts", select: type(coalesce(row.title, "title!"), :string)
```

```elixir

** (Ecto.Query.CompileError) `type(coalesce(row.title(), "title!"), :string)` is not a valid query expression.

* If you intended to call a database function, please check the documentation
  for Ecto.Query to see the supported database expressions

* If you intended to call an Elixir function or introduce a value,
  you need to explicitly interpolate it with ^

    (ecto) expanding macro: Ecto.Query.select/3
    iex:13: (file)
    (ecto) expanding macro: Ecto.Query.from/2
    iex:13: (file)
```

### Expected behavior

I'll look into it an open a PR w/ a fix shortly if possible, just posting the issue in case anyone knows off of the top of their head why it doesn't work :)

**Comment by zachdaniel** [comment]
It looks like `type` is factored out of the query using `prewalk`?

**Comment by josevalim** [comment]
@zachdaniel we support type only on a handful of expressions. Is there any reason why we want to support it on coalesce? I would rather not support it.

**Comment by josevalim** [comment]
Closing in favor of the PR.

**Comment by coop** [comment]
I hate to dig up the past but the PR wasn't linked and I've had trouble finding it. I've got a situation where I would like to do:

```
from m in query,
  join: a in assoc(m, :account),
  select_merge: %{current_offset_amount: type(coalesce(a.balance, 0), Money.Ecto.Amount.Type)}
```

which doesn't work. Is there a different way to write the query? /cc @zachdaniel

**Comment by josevalim** [comment]
Did you try latest Ecto? Otherwise you will have to write that as a fragment:

     type(fragment("...", a.balance), Money.Ecto.Amount.Type)}

**Comment by coop** [comment]
It does not work with the latest Ecto (3.5.7):

```
== Compilation error in file lib/plutus/properties/mortgage.ex ==
** (Ecto.Query.CompileError) the first argument of type/2 must be one of:

  * interpolations, such as ^value
  * fields, such as p.foo or field(p)
  * fragments, such fragment("foo(?)", value)
  * an arithmetic expression (+, -, *, /)
  * an aggregation or window expression (avg, count, min, max, sum, over, filter)

Got: coalesce(a.balance, 0)
```

Using `fragment` does work:

```
from m in query,
  join: a in assoc(m, :account),
  select_merge: %{current_offset_amount: type(fragment("coalesce(?, ?)", a.balance, 0), Money.Ecto.Amount.Type)}
```

**Comment by LostKobrakai** [comment]
Is this supposed to be working? I still see this issue on the latest ecto version:
```
== Compilation error in file lib/edith/billing.ex ==
** (Ecto.Query.CompileError) the first argument of type/2 must be one of:

  * interpolations, such as ^value
  * fields, such as p.foo or field(p)
  * fragments, such fragment("foo(?)", value)
  * an arithmetic expression (+, -, *, /)
  * an aggregation or window expression (avg, count, min, max, sum, over, filter)
  * access/json paths (p.column[0].field)

Got: coalesce(sum(qcwp.amount), 0)
```
```
* ecto (Hex package) (mix)
  locked at 3.7.1 (ecto) d36e5b39
* ecto_sql (Hex package) (mix)
  locked at 3.7.0 (ecto_sql) a26135df
```

**Comment by josevalim** [comment]
I think my poor english failed all of us. Maybe I wanted to say a PR is welcome? :D

In any case, yes, a PR is welcome. :)
